### ISSUE TITLE
Create KDP template

### ISSUE THREAD

**Issue by realshuting** [kyverno/KDP#7]
It would be good to create a KDP template that enforces mandatory content while proposing. It also helps reviewers to better understand the design.

This can be an example:
```
# Kyverno Design Proposal - <name of the proposal>

Author: [author name](GitHub handle)

PR: link to the issue

## Contents
- Overview/Introduction
- Requirements
- Proposal
- Examples
- Alternatives (optional)
- Implementations (optional) - will be tracked via the task list
```

cc @chipzoller

**Comment by chipzoller** [comment]
Assigned

**Comment by Namanl2001** [comment]
Few sections which could be added:

- What
- Why
- Pitfalls of the current solution
- Goals
- Non-Goals
- How
- Alternatives
- Action Plan
